### ISSUE TITLE
versioning!

### ISSUE THREAD

**Issue by chazcb** [janmonschke/backbone-couchdb#12]
Hi janmonschke,
Thanks for contributing this great adapter. I was hoping you could start versioning so I can properly track changes on my teams' CDN. I'm looking forward to contributing to this as I start to work more with couch. Thanks so much!

**Comment by janmonschke** [comment]
Sure, will update the docs and will add version numbers soon.
Did not find the time to do that after the last release.

**Comment by janmonschke** [comment]
Added versioning. Is the format appropriate?

**Comment by chazcb** [comment]
Looks good to me. You may want to $git tag 1.0 the repo as well so folks looking through the history can load older versions (for dependency issues, etc).

**Comment by janmonschke** [comment]
Created the tag locally and hoped that git would upload it automatically. Didn't know you have to do `git push --tags` to upload tags.
