### ISSUE TITLE
Unpatched Backbone.Model still remians in Backbone.Collection::model

### ISSUE THREAD

**Issue by dwt** [janmonschke/backbone-couchdb#27]
Which is a pain because it means you have to use Backbone.Collection with custom subclasses (or fix the error yourself with

Backbone.Collection::model = Backbone.Model

**Comment by janmonschke** [comment]
Does it work for you now?

**Comment by dwt** [comment]
I did apply the fix myself already, but I'll get back to you on the next update of backbone.couchdb.
