### ISSUE TITLE
Add the option to use lists and shows

### ISSUE THREAD

**Issue by kurtmilam** [janmonschke/backbone-couchdb#36]
This would give developers access to the extra power provided by lists and shows - lists, especially. For instance, lists give you access to the userCtx - the name of the user making the query. This can be useful when you're trying to filter records returned to a collection based on the logged in user making the request.

I think this could be implemented relatively easily, either by listening for list or show definitions in options, or by adding a list attribute to collections and a show attribute to models.

Would you entertain a pull request along these lines?

Thanks for the nice module, btw...

**Comment by janmonschke** [comment]
This can be really useful I think and I would love to have someone doing a pull-request for that!

**Comment by kurtmilam** [comment]
The pull request included in issue #37 adds support for CouchDB lists.
