### ISSUE TITLE
jquery.couch.js in README defunct

### ISSUE THREAD

**Issue by dvberkel** [janmonschke/backbone-couchdb#40]
The jquery.couch.js link in the [README](https://github.com/janmonschke/backbone-couchdb/blob/master/README.md) points to a defunct url: https://github.com/apache/couchdb/blob/trunk/share/www/script/jquery.couch.js

I searched around for a jquery.couch.js and found one by [daleharvey](https://github.com/daleharvey/jquery.couch.js). Maybe they are compatible/identical and that link could be used instead.

**Comment by janmonschke** [comment]
Thx, added it to the README.

8b05b31254e4ede036e988629a88a0fba6a33693
