### ISSUE TITLE
Undeclared variable error in error handler

### ISSUE THREAD

**Issue by dwt** [janmonschke/backbone-couchdb#57]
Hi there,

I believe that in line https://github.com/janmonschke/backbone-couchdb/blob/master/backbone-couchdb.js#L192

the error variable should actually be e

At least it fails for me with that error.

**Comment by janmonschke** [comment]
:+1:

**Comment by dwt** [comment]
:-)

Not sure if thats the whole fix, looking at the other error handlers this might be required:

```

diff --git a/js/vendor/backbone-couchdb-1.2.js b/js/vendor/backbone-couchdb-1.2.
index 5c23a4d..be89ebe 100644
--- a/js/vendor/backbone-couchdb-1.2.js
+++ b/js/vendor/backbone-couchdb-1.2.js
@@ -168,9 +168,9 @@ backbone-couchdb.js is licensed under the MIT license.
         success: function() {
           return opts.success();
         },
-        error: function(nr, req, e) {
+        error: function(status, error, reason) {
           var res;
-          if (e === "deleted") {
+          if (error === "deleted") {
             opts.success();
             return opts.complete();
           } else {
```

**Comment by dwt** [comment]
:-) May I redirect your attention to the line that also renames status and reason? As those are also used in the error handler - but I have no idea if the order of the arguments differs in this error handler to all other error handlers.

**Comment by janmonschke** [comment]
Didn't see that ^^

Should be fixed now, what do you say?

**Comment by dwt** [comment]
looks good.
