### ISSUE TITLE
no metadata.json

### ISSUE THREAD

**Issue by benoitc** [janmonschke/backbone-couchdb#8]
right now backbone-couchdb can't be installed via the vendor command of couchapp script. Would be cool if you can add metadata.json file to your repo. Ex:

https://github.com/couchapp/couchapp/blob/master/vendor/metadata.json

**Comment by janmonschke** [comment]
like this? 7e739888ca01ee703b48956c01d097aee56eba3e

**Comment by benoitc** [comment]
mmm It should be at the top of your repo I think. Just saw that you need to install a view though which isn't possible right now. I'm opening a ticket for that so we could install easily your vendor :)

**Comment by janmonschke** [comment]
Will move it to the top of the repo ;)

**Comment by janmonschke** [comment]
correct now? db5100e2d863e8c32f7cf488d6b725c96cb0a574
